name: causal

dependencies:
    - python==3.6.7
    - pip:
        - numpy==1.16.0
        - gym==0.10.9
        - matplotlib==3.1.3
        - opencv-python
        - ray==0.6.1
        - tensorflow==1.12.0
        - scipy==1.2.0
        - setproctitle
        - psutil
        - lz4

