name: causal

dependencies:
    - python==3.7.9
    - pip:
        - gym==0.10.9
        - matplotlib==3.1.3
        - opencv-python
        - ray==0.6.1
        - tensorflow==1.15.4
        - scipy==1.2.0
        - setproctitle
        - psutil
        - lz4

